--- 
- 
  connection: network_cli
  gather_facts: false
  hosts: 
    - "{{ device_id }}"
  name: "Netbox Webhook Testing"
  tasks: 
    - 
      ? "Cisco.ISR 1111-8P.GigabitEthernet0/0/0"
      : 
        config: 
          - 
            access: 
              vlan: "{{ vlan_id }}"
            name: "{{ interface_id }}"
        state: replaced
      name: "ISR 1111-8P Interface"
